import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { describe, expect, it } from 'vitest';

// 用例从**仓库根**定位：拆包后源码分散在 packages/*/src，不再有单一 src/ 根。
// 注意：jsdom 环境下全局 `URL` 被替换过，`new URL(相对路径, import.meta.url)` 会解析到 dev-server 的
// `http://localhost:3000/@fs/…`；所以这里一律用 node:path / node:url 显式计算。
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../');
const existsInSrc = (path) => existsSync(join(ROOT, path));
const importFromSrc = (path) => import(pathToFileURL(join(ROOT, path)).href);
const readFromSrc = (path) => readFileSync(join(ROOT, path), 'utf8');

// 本套用例会动态导入整库并逐个断言文件结构，并行满载时贴近 vitest 默认 5s 超时，故显式放宽。
describe('foundation module structure', { timeout: 30000 }, () => {
  it('keeps large modules compact with concise file names and domain entrypoints', async () => {
    expect(existsInSrc('packages/yoya-core/src/core/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-core/src/core/node.js')).toBe(true);
    expect(existsInSrc('packages/contract/tests/core/node.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-core/src/core/i18n.js')).toBe(true);
    expect(existsInSrc('packages/yoya-core/src/html/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-core/src/svg/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-core/src/svg/icons.js')).toBe(true);
    expect(existsInSrc('packages/yoya-core/src/svg/icons.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/layout/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/actions/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/actions/button.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/actions/context-menu.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/actions/dropdown-menu.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/anchor.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/anchor.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/breadcrumb.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/breadcrumb.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/menu.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/steps.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/steps.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/tabs.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation/tabs.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/message.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/dialog.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/dialog.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/tooltip.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/tooltip.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/controls.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/rate.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/rate.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/upload.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/upload.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/avatar-upload.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form/avatar-upload.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/badge.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/badge.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/code.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/detail.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/pagination.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/progress.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/progress.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/vscroll.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/vscroll.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/carousel.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/carousel.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/surface.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/table.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/table.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/tree.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/avatar.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/avatar.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/tree.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/chart.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/chart.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/code-block.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display/code-block.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/async/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/async/dynamic-loader.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/async/dynamic-loader.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/router/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/router/router.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/router/router.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/chart/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/chart/echart.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/chart/echart.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/chart/echarts.min.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/echart.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/three/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/three/three.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/three/three.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/three.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/ssr.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/message-manager.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback/message-manager.test.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/components/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-core/src/index.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/ui.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/yoya.ui.css')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/actions.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/navigation.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/feedback.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/form.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/data-display.js')).toBe(true);
    expect(existsInSrc('packages/yoya-ui/src/async.js')).toBe(true);

    expect(existsInSrc('src/testing/gates/chart.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/chart.test.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/three.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/code-block.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/code-block.test.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/dynamic-loader.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/dynamic-loader.test.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/message-manager.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/message-manager.test.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/router.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/router.test.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/attributes.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/dom.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/element-node.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/factory.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/html-escape.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/styles.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/view-node.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/core/view-node.test.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/html/html-element-node.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/svg/svg-element-node.js')).toBe(false);
    expect(existsInSrc('src/testing/gates/elements')).toBe(false);

    const componentsEntry = readFromSrc('packages/yoya-ui/src/components/index.js');
    expect(componentsEntry).not.toMatch(/^export class /m);
    expect(componentsEntry).not.toMatch(/^export function /m);
    expect(componentsEntry).not.toMatch(/^export const toast\b/m);

    const api = await importFromSrc('packages/yoya-ui/src/index.js');
    const html = await importFromSrc('packages/yoya-core/src/html/index.js');
    const svg = await importFromSrc('packages/yoya-core/src/svg/index.js');
    const actions = await importFromSrc('packages/yoya-ui/src/actions/index.js');
    const navigation = await importFromSrc('packages/yoya-ui/src/navigation/index.js');
    const feedback = await importFromSrc('packages/yoya-ui/src/feedback/index.js');
    const form = await importFromSrc('packages/yoya-ui/src/form/index.js');
    const dataDisplay = await importFromSrc('packages/yoya-ui/src/data-display/index.js');
    const asyncViews = await importFromSrc('packages/yoya-ui/src/async/index.js');
    const routerModule = await importFromSrc('packages/yoya-ui/src/router/index.js');
    const components = await importFromSrc('packages/yoya-ui/src/components/index.js');
    const coreEntry = await importFromSrc('packages/yoya-core/src/index.js');
    const coreTools = await importFromSrc('packages/yoya-core/src/tools.js');
    const coreDev = await importFromSrc('packages/yoya-core/src/dev.js');
    const uiSvgEntry = await importFromSrc('packages/yoya-ui/src/svg.js');
    const uiToolsEntry = await importFromSrc('packages/yoya-ui/src/tools.js');
    const uiDevEntry = await importFromSrc('packages/yoya-ui/src/dev.js');
    const uiEntry = await importFromSrc('packages/yoya-ui/src/ui.js');
    const actionsEntry = await importFromSrc('packages/yoya-ui/src/actions.js');
    const navigationEntry = await importFromSrc('packages/yoya-ui/src/navigation.js');
    const feedbackEntry = await importFromSrc('packages/yoya-ui/src/feedback.js');
    const formEntry = await importFromSrc('packages/yoya-ui/src/form.js');
    const dataDisplayEntry = await importFromSrc('packages/yoya-ui/src/data-display.js');
    const asyncEntry = await importFromSrc('packages/yoya-ui/src/async.js');
    const routerEntry = await importFromSrc('packages/yoya-ui/src/router.js');
    const echartEntry = await importFromSrc('packages/yoya-ui/src/echart.js');
    const threeEntry = await importFromSrc('packages/yoya-ui/src/three.js');

    expect(api.div).toBe(html.div);
    expect(api.svg).toBe(svg.svg);
    expect(api.svgs).toBe(svg.svgs);
    expect(api.flex).toBeTypeOf('function');
    expect(api.mobileLayout).toBeTypeOf('function');
    expect(api.vMobileLayout).toBeTypeOf('function');
    expect(api.router).toBe(routerModule.router);
    expect(api.createRouter).toBe(routerModule.createRouter);
    expect(api.Router).toBe(routerModule.Router);
    expect(api.ElementNode).toBeTypeOf('function');
    expect(api.HtmlElementNode).toBeTypeOf('function');
    expect(api.SvgElementNode).toBeTypeOf('function');
    expect(api.vEchart).toBeUndefined();
    expect(api.vThree).toBeUndefined();
    expect(api.SearchOutlined).toBeTypeOf('function');
    expect(api.circle).toBeUndefined();
    expect(api.vButton).toBe(actions.vButton);
    expect(api.vButtons).toBe(actions.vButtons);
    expect(api.vFloatButton).toBe(actions.vFloatButton);
    expect(api.vMenu).toBe(navigation.vMenu);
    expect(api.vAnchor).toBe(navigation.vAnchor);
    expect(api.vAnchorItem).toBe(navigation.vAnchorItem);
    expect(api.VAnchor).toBe(navigation.VAnchor);
    expect(api.VAnchorItem).toBe(navigation.VAnchorItem);
    expect(api.vBreadcrumb).toBe(navigation.vBreadcrumb);
    expect(api.vBreadcrumbItem).toBe(navigation.vBreadcrumbItem);
    expect(api.VBreadcrumb).toBe(navigation.VBreadcrumb);
    expect(api.VBreadcrumbItem).toBe(navigation.VBreadcrumbItem);
    expect(api.vSteps).toBe(navigation.vSteps);
    expect(api.vStep).toBe(navigation.vStep);
    expect(api.VSteps).toBe(navigation.VSteps);
    expect(api.VStep).toBe(navigation.VStep);
    expect(api.vTabs).toBe(navigation.vTabs);
    expect(api.vTab).toBe(navigation.vTab);
    expect(api.VTabs).toBe(navigation.VTabs);
    expect(api.VTab).toBe(navigation.VTab);
    expect(api.toast).toBe(feedback.toast);
    expect(api.vMessageManager).toBe(feedback.vMessageManager);
    expect(api.vDialog).toBe(feedback.vDialog);
    expect(api.vTooltip).toBe(feedback.vTooltip);
    expect(api.VTooltip).toBe(feedback.VTooltip);
    expect(api.vForm).toBe(form.vForm);
    expect(api.vRadio).toBe(form.vRadio);
    expect(api.vRadios).toBe(form.vRadios);
    expect(api.vUpload).toBe(form.vUpload);
    expect(api.VUpload).toBe(form.VUpload);
    expect(api.vRate).toBe(form.vRate);
    expect(api.VRate).toBe(form.VRate);
    expect(api.vAvatarUpload).toBe(form.vAvatarUpload);
    expect(api.VAvatarUpload).toBe(form.VAvatarUpload);
    expect(api.vTable).toBe(dataDisplay.vTable);
    expect(api.vThead).toBe(dataDisplay.vThead);
    expect(api.vTbody).toBe(dataDisplay.vTbody);
    expect(api.vTfoot).toBe(dataDisplay.vTfoot);
    expect(api.vTr).toBe(dataDisplay.vTr);
    expect(api.vTh).toBe(dataDisplay.vTh);
    expect(api.vTd).toBe(dataDisplay.vTd);
    expect(api.vTree).toBe(dataDisplay.vTree);
    expect(api.vTreeNode).toBe(dataDisplay.vTreeNode);
    expect(api.VTreeNode).toBe(dataDisplay.VTreeNode);
    expect(api.vBadge).toBe(dataDisplay.vBadge);
    expect(api.VBadge).toBe(dataDisplay.VBadge);
    expect(api.vProgress).toBe(dataDisplay.vProgress);
    expect(api.VProgress).toBe(dataDisplay.VProgress);
    expect(api.vScroll).toBe(dataDisplay.vScroll);
    expect(api.VScroll).toBe(dataDisplay.VScroll);
    expect(api.vCarousel).toBe(dataDisplay.vCarousel);
    expect(api.VCarousel).toBe(dataDisplay.VCarousel);
    expect(api.vAvatar).toBe(dataDisplay.vAvatar);
    expect(api.VAvatar).toBe(dataDisplay.VAvatar);
    expect(api.vChart).toBe(dataDisplay.vChart);
    expect(api.codeBlock).toBe(dataDisplay.codeBlock);
    expect(api.vDynamicLoader).toBe(asyncViews.vDynamicLoader);
    expect(api.vCard).toBe(components.vCard);
    expect(api.vButton).toBe(components.vButton);
    expect(api.vButtons).toBe(components.vButtons);
    expect(api.vFloatButton).toBe(components.vFloatButton);
    expect(api.vRadio).toBe(components.vRadio);
    expect(api.vRadios).toBe(components.vRadios);
    expect(api.vAnchor).toBe(components.vAnchor);
    expect(api.vAnchorItem).toBe(components.vAnchorItem);
    expect(api.vBreadcrumb).toBe(components.vBreadcrumb);
    expect(api.vBreadcrumbItem).toBe(components.vBreadcrumbItem);
    expect(api.vSteps).toBe(components.vSteps);
    expect(api.vTabs).toBe(components.vTabs);
    expect(api.vBadge).toBe(components.vBadge);
    expect(api.vTree).toBe(components.vTree);
    expect(api.vTreeNode).toBe(components.vTreeNode);
    expect(api.vProgress).toBe(components.vProgress);
    expect(api.vScroll).toBe(components.vScroll);
    expect(api.vCarousel).toBe(components.vCarousel);
    expect(api.vTooltip).toBe(components.vTooltip);
    expect(api.toast).toBe(components.toast);
    expect(api.vThead).toBe(components.vThead);
    expect(api.vTbody).toBe(components.vTbody);
    expect(api.vTfoot).toBe(components.vTfoot);
    expect(api.vTr).toBe(components.vTr);
    expect(api.vTh).toBe(components.vTh);
    expect(api.vTd).toBe(components.vTd);
    expect(coreEntry.div).toBe(html.div);
    // 0.8 起：svg 与 i18n/a11y/theme 不再挂 core 主入口（主入口只留渲染必需的原语）
    expect(coreEntry.svg).toBeUndefined();
    expect(coreEntry.svgs).toBeUndefined();
    expect(coreEntry.SearchOutlined).toBeUndefined();
    expect(coreEntry.createI18n).toBeUndefined();
    expect(coreEntry.initYoyaTheme).toBeUndefined();
    expect(coreEntry.HtmlElementNode).toBeTypeOf('function');
    // 新入口面：svg / tools / dev 各自成入口，且与实现同源
    expect(coreTools.createI18n).toBeTypeOf('function');
    expect(coreTools.initYoyaTheme).toBeTypeOf('function');
    expect(coreTools.announce).toBeTypeOf('function');
    expect(coreDev.enableDevtools).toBeTypeOf('function');
    expect(uiSvgEntry.svgs).toBe(svg.svgs);
    expect(uiSvgEntry.SearchOutlined).toBeTypeOf('function');
    expect(uiToolsEntry.createI18n).toBe(coreTools.createI18n);
    expect(uiDevEntry.enableDevtools).toBe(coreDev.enableDevtools);
    expect(coreEntry.vButton).toBeUndefined();
    expect(coreEntry.vButtons).toBeUndefined();
    expect(coreEntry.vFloatButton).toBeUndefined();
    expect(coreEntry.vRadio).toBeUndefined();
    expect(coreEntry.vRadios).toBeUndefined();
    expect(coreEntry.flex).toBeUndefined();
    expect(uiEntry.div).toBeUndefined();
    expect(uiEntry.SearchOutlined).toBeUndefined();
    expect(uiEntry.svgs).toBeUndefined();
    expect(uiEntry.vButton).toBe(actions.vButton);
    expect(uiEntry.vButtons).toBe(actions.vButtons);
    expect(uiEntry.vFloatButton).toBe(actions.vFloatButton);
    expect(uiEntry.vRadio).toBe(form.vRadio);
    expect(uiEntry.vRadios).toBe(form.vRadios);
    expect(uiEntry.flex).toBeTypeOf('function');
    expect(uiEntry.mobileLayout).toBeTypeOf('function');
    expect(uiEntry.toast).toBe(feedback.toast);
    expect(uiEntry.vTooltip).toBe(feedback.vTooltip);
    expect(uiEntry.vScroll).toBe(dataDisplay.vScroll);
    expect(uiEntry.vCarousel).toBe(dataDisplay.vCarousel);
    expect(uiEntry.vDigitalBoard).toBe(dataDisplay.vDigitalBoard);
    expect(uiEntry.vDigitalBoardItem).toBe(dataDisplay.vDigitalBoardItem);
    expect(uiEntry.vSparkline).toBe(dataDisplay.vSparkline);
    expect(uiEntry.vTrendCard).toBe(dataDisplay.vTrendCard);
    expect(uiEntry.vRingStat).toBe(dataDisplay.vRingStat);
    expect(uiEntry.vGauge).toBe(dataDisplay.vGauge);
    expect(uiEntry.vTimeline).toBe(dataDisplay.vTimeline);
    expect(uiEntry.vTimelineItem).toBe(dataDisplay.vTimelineItem);
    expect(uiEntry.vDynamicLoader).toBe(asyncViews.vDynamicLoader);
    expect(uiEntry.vUpload).toBe(form.vUpload);
    expect(uiEntry.vRate).toBe(form.vRate);
    expect(actionsEntry.vButton).toBe(actions.vButton);
    expect(actionsEntry.vForm).toBeUndefined();
    expect(actionsEntry.flex).toBeUndefined();
    expect(navigationEntry.vMenu).toBe(navigation.vMenu);
    expect(navigationEntry.vButton).toBeUndefined();
    expect(feedbackEntry.toast).toBe(feedback.toast);
    expect(feedbackEntry.vForm).toBeUndefined();
    expect(formEntry.vForm).toBe(form.vForm);
    expect(formEntry.vButton).toBeUndefined();
    expect(dataDisplayEntry.vTable).toBe(dataDisplay.vTable);
    expect(dataDisplayEntry.vForm).toBeUndefined();
    expect(asyncEntry.vDynamicLoader).toBe(asyncViews.vDynamicLoader);
    expect(asyncEntry.vTable).toBeUndefined();
    expect(echartEntry.vEchart).toBeTypeOf('function');
    expect(echartEntry.VEchart).toBeTypeOf('function');
    expect(threeEntry.vThree).toBeTypeOf('function');
    expect(threeEntry.VThree).toBeTypeOf('function');
    expect(uiEntry.router).toBeUndefined();
    expect(routerEntry.createRouter).toBe(routerModule.createRouter);
    expect(routerEntry.Router).toBe(routerModule.Router);
    expect(routerEntry.renderToString).toBeTypeOf('function');
    expect(routerEntry.hydrate).toBeTypeOf('function');
    expect(routerEntry.vButton).toBeUndefined();
    expect(routerEntry.div).toBeUndefined();
  });

  it('keeps core helpers available through the core entry', async () => {
    const api = await importFromSrc('packages/yoya-ui/src/index.js');

    expect(api.escapeHtml('<node attr="value">')).toBe('&lt;node attr=&quot;value&quot;&gt;');
    expect(api.resolveTarget(document.body)).toBe(document.body);
    expect(api.SVG_NAMESPACE).toBe('http://www.w3.org/2000/svg');
  });
});
