import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const existsInSrc = (path) => existsSync(new URL(path, import.meta.url));
const importFromSrc = (path) => import(new URL(path, import.meta.url).href);
const readFromSrc = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');

describe('foundation module structure', () => {
  it('keeps large modules compact with concise file names and domain entrypoints', async () => {
    expect(existsInSrc('./core/index.js')).toBe(true);
    expect(existsInSrc('./core/node.js')).toBe(true);
    expect(existsInSrc('./core/node.test.js')).toBe(true);
    expect(existsInSrc('./core/i18n.js')).toBe(true);
    expect(existsInSrc('./html/index.js')).toBe(true);
    expect(existsInSrc('./svg/index.js')).toBe(true);
    expect(existsInSrc('./svg/icons.js')).toBe(true);
    expect(existsInSrc('./svg/icons.test.js')).toBe(true);
    expect(existsInSrc('./layout/index.js')).toBe(true);
    expect(existsInSrc('./actions/index.js')).toBe(true);
    expect(existsInSrc('./actions/button.js')).toBe(true);
    expect(existsInSrc('./actions/context-menu.js')).toBe(true);
    expect(existsInSrc('./actions/dropdown-menu.js')).toBe(true);
    expect(existsInSrc('./navigation/index.js')).toBe(true);
    expect(existsInSrc('./navigation/anchor.js')).toBe(true);
    expect(existsInSrc('./navigation/anchor.test.js')).toBe(true);
    expect(existsInSrc('./navigation/breadcrumb.js')).toBe(true);
    expect(existsInSrc('./navigation/breadcrumb.test.js')).toBe(true);
    expect(existsInSrc('./navigation/menu.js')).toBe(true);
    expect(existsInSrc('./navigation/steps.js')).toBe(true);
    expect(existsInSrc('./navigation/steps.test.js')).toBe(true);
    expect(existsInSrc('./feedback/index.js')).toBe(true);
    expect(existsInSrc('./feedback/message.js')).toBe(true);
    expect(existsInSrc('./feedback/dialog.js')).toBe(true);
    expect(existsInSrc('./feedback/dialog.test.js')).toBe(true);
    expect(existsInSrc('./form/index.js')).toBe(true);
    expect(existsInSrc('./form/controls.js')).toBe(true);
    expect(existsInSrc('./form/upload.js')).toBe(true);
    expect(existsInSrc('./form/upload.test.js')).toBe(true);
    expect(existsInSrc('./form/avatar-upload.js')).toBe(true);
    expect(existsInSrc('./form/avatar-upload.test.js')).toBe(true);
    expect(existsInSrc('./data-display/index.js')).toBe(true);
    expect(existsInSrc('./data-display/badge.js')).toBe(true);
    expect(existsInSrc('./data-display/badge.test.js')).toBe(true);
    expect(existsInSrc('./data-display/code.js')).toBe(true);
    expect(existsInSrc('./data-display/detail.js')).toBe(true);
    expect(existsInSrc('./data-display/pagination.js')).toBe(true);
    expect(existsInSrc('./data-display/surface.js')).toBe(true);
    expect(existsInSrc('./data-display/table.js')).toBe(true);
    expect(existsInSrc('./data-display/tree.js')).toBe(true);
    expect(existsInSrc('./data-display/avatar.js')).toBe(true);
    expect(existsInSrc('./data-display/avatar.test.js')).toBe(true);
    expect(existsInSrc('./data-display/tree.test.js')).toBe(true);
    expect(existsInSrc('./data-display/chart.js')).toBe(true);
    expect(existsInSrc('./data-display/chart.test.js')).toBe(true);
    expect(existsInSrc('./data-display/code-block.js')).toBe(true);
    expect(existsInSrc('./data-display/code-block.test.js')).toBe(true);
    expect(existsInSrc('./async/index.js')).toBe(true);
    expect(existsInSrc('./async/dynamic-loader.js')).toBe(true);
    expect(existsInSrc('./async/dynamic-loader.test.js')).toBe(true);
    expect(existsInSrc('./router/index.js')).toBe(true);
    expect(existsInSrc('./router/router.js')).toBe(true);
    expect(existsInSrc('./router/router.test.js')).toBe(true);
    expect(existsInSrc('./chart/index.js')).toBe(true);
    expect(existsInSrc('./chart/echart.js')).toBe(true);
    expect(existsInSrc('./chart/echart.test.js')).toBe(true);
    expect(existsInSrc('./chart/echarts.min.js')).toBe(true);
    expect(existsInSrc('./yoya.echart.js')).toBe(true);
    expect(existsInSrc('./feedback/message-manager.js')).toBe(true);
    expect(existsInSrc('./feedback/message-manager.test.js')).toBe(true);
    expect(existsInSrc('./components/index.js')).toBe(true);
    expect(existsInSrc('./yoya.core.js')).toBe(true);
    expect(existsInSrc('./yoya.ui.js')).toBe(true);
    expect(existsInSrc('./yoya.ui.css')).toBe(true);

    expect(existsInSrc('./chart.js')).toBe(false);
    expect(existsInSrc('./chart.test.js')).toBe(false);
    expect(existsInSrc('./code-block.js')).toBe(false);
    expect(existsInSrc('./code-block.test.js')).toBe(false);
    expect(existsInSrc('./dynamic-loader.js')).toBe(false);
    expect(existsInSrc('./dynamic-loader.test.js')).toBe(false);
    expect(existsInSrc('./message-manager.js')).toBe(false);
    expect(existsInSrc('./message-manager.test.js')).toBe(false);
    expect(existsInSrc('./router.js')).toBe(false);
    expect(existsInSrc('./router.test.js')).toBe(false);
    expect(existsInSrc('./core/attributes.js')).toBe(false);
    expect(existsInSrc('./core/dom.js')).toBe(false);
    expect(existsInSrc('./core/element-node.js')).toBe(false);
    expect(existsInSrc('./core/factory.js')).toBe(false);
    expect(existsInSrc('./core/html-escape.js')).toBe(false);
    expect(existsInSrc('./core/styles.js')).toBe(false);
    expect(existsInSrc('./core/view-node.js')).toBe(false);
    expect(existsInSrc('./core/view-node.test.js')).toBe(false);
    expect(existsInSrc('./html/html-element-node.js')).toBe(false);
    expect(existsInSrc('./svg/svg-element-node.js')).toBe(false);
    expect(existsInSrc('./elements')).toBe(false);

    const componentsEntry = readFromSrc('./components/index.js');
    expect(componentsEntry).not.toMatch(/^export class /m);
    expect(componentsEntry).not.toMatch(/^export function /m);
    expect(componentsEntry).not.toMatch(/^export const toast\b/m);

    const api = await importFromSrc('./index.js');
    const html = await importFromSrc('./html/index.js');
    const svg = await importFromSrc('./svg/index.js');
    const actions = await importFromSrc('./actions/index.js');
    const navigation = await importFromSrc('./navigation/index.js');
    const feedback = await importFromSrc('./feedback/index.js');
    const form = await importFromSrc('./form/index.js');
    const dataDisplay = await importFromSrc('./data-display/index.js');
    const asyncViews = await importFromSrc('./async/index.js');
    const routerModule = await importFromSrc('./router/index.js');
    const components = await importFromSrc('./components/index.js');
    const coreEntry = await importFromSrc('./yoya.core.js');
    const uiEntry = await importFromSrc('./yoya.ui.js');
    const echartEntry = await importFromSrc('./yoya.echart.js');

    expect(api.div).toBe(html.div);
    expect(api.svg).toBe(svg.svg);
    expect(api.flex).toBeTypeOf('function');
    expect(api.mobileLayout).toBeTypeOf('function');
    expect(api.vMobileLayout).toBeTypeOf('function');
    expect(api.router).toBe(routerModule.router);
    expect(api.createRouter).toBe(routerModule.createRouter);
    expect(api.Router).toBe(routerModule.Router);
    expect(api.ElementNode).toBeTypeOf('function');
    expect(api.HtmlElementNode).toBeTypeOf('function');
    expect(api.SvgElementNode).toBeTypeOf('function');
    expect(api.vEchart).toBeUndefined();
    expect(api.SearchOutlined).toBeTypeOf('function');
    expect(api.circle).toBeUndefined();
    expect(api.vButton).toBe(actions.vButton);
    expect(api.vMenu).toBe(navigation.vMenu);
    expect(api.vAnchor).toBe(navigation.vAnchor);
    expect(api.vAnchorItem).toBe(navigation.vAnchorItem);
    expect(api.VAnchor).toBe(navigation.VAnchor);
    expect(api.VAnchorItem).toBe(navigation.VAnchorItem);
    expect(api.vBreadcrumb).toBe(navigation.vBreadcrumb);
    expect(api.vBreadcrumbItem).toBe(navigation.vBreadcrumbItem);
    expect(api.VBreadcrumb).toBe(navigation.VBreadcrumb);
    expect(api.VBreadcrumbItem).toBe(navigation.VBreadcrumbItem);
    expect(api.vSteps).toBe(navigation.vSteps);
    expect(api.vStep).toBe(navigation.vStep);
    expect(api.VSteps).toBe(navigation.VSteps);
    expect(api.VStep).toBe(navigation.VStep);
    expect(api.toast).toBe(feedback.toast);
    expect(api.vMessageManager).toBe(feedback.vMessageManager);
    expect(api.vDialog).toBe(feedback.vDialog);
    expect(api.vForm).toBe(form.vForm);
    expect(api.vUpload).toBe(form.vUpload);
    expect(api.VUpload).toBe(form.VUpload);
    expect(api.vAvatarUpload).toBe(form.vAvatarUpload);
    expect(api.VAvatarUpload).toBe(form.VAvatarUpload);
    expect(api.vTable).toBe(dataDisplay.vTable);
    expect(api.vTree).toBe(dataDisplay.vTree);
    expect(api.vTreeNode).toBe(dataDisplay.vTreeNode);
    expect(api.VTreeNode).toBe(dataDisplay.VTreeNode);
    expect(api.vBadge).toBe(dataDisplay.vBadge);
    expect(api.VBadge).toBe(dataDisplay.VBadge);
    expect(api.vAvatar).toBe(dataDisplay.vAvatar);
    expect(api.VAvatar).toBe(dataDisplay.VAvatar);
    expect(api.vChart).toBe(dataDisplay.vChart);
    expect(api.codeBlock).toBe(dataDisplay.codeBlock);
    expect(api.vDynamicLoader).toBe(asyncViews.vDynamicLoader);
    expect(api.vCard).toBe(components.vCard);
    expect(api.vButton).toBe(components.vButton);
    expect(api.vAnchor).toBe(components.vAnchor);
    expect(api.vAnchorItem).toBe(components.vAnchorItem);
    expect(api.vBreadcrumb).toBe(components.vBreadcrumb);
    expect(api.vBreadcrumbItem).toBe(components.vBreadcrumbItem);
    expect(api.vSteps).toBe(components.vSteps);
    expect(api.vBadge).toBe(components.vBadge);
    expect(api.vTree).toBe(components.vTree);
    expect(api.vTreeNode).toBe(components.vTreeNode);
    expect(api.toast).toBe(components.toast);
    expect(coreEntry.div).toBe(html.div);
    expect(coreEntry.svg).toBe(svg.svg);
    expect(coreEntry.HtmlElementNode).toBeTypeOf('function');
    expect(coreEntry.SearchOutlined).toBeTypeOf('function');
    expect(coreEntry.vButton).toBeUndefined();
    expect(coreEntry.flex).toBeUndefined();
    expect(uiEntry.div).toBe(html.div);
    expect(uiEntry.SearchOutlined).toBeTypeOf('function');
    expect(uiEntry.vButton).toBe(actions.vButton);
    expect(uiEntry.flex).toBeTypeOf('function');
    expect(uiEntry.mobileLayout).toBeTypeOf('function');
    expect(uiEntry.toast).toBe(feedback.toast);
    expect(uiEntry.vDynamicLoader).toBe(asyncViews.vDynamicLoader);
    expect(uiEntry.vUpload).toBe(form.vUpload);
    expect(echartEntry.vEchart).toBeTypeOf('function');
    expect(echartEntry.VEchart).toBeTypeOf('function');
    expect(uiEntry.router).toBe(routerModule.router);
  });

  it('keeps core helpers available through the core entry', async () => {
    const api = await importFromSrc('./index.js');

    expect(api.escapeHtml('<node attr="value">')).toBe('&lt;node attr=&quot;value&quot;&gt;');
    expect(api.resolveTarget(document.body)).toBe(document.body);
    expect(api.SVG_NAMESPACE).toBe('http://www.w3.org/2000/svg');
  });
});
